[build]
  command = "npm install --platform=linux --arch=x64 && npm install @rollup/rollup-linux-x64-gnu --platform=linux --arch=x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PLATFORM = "linux"
  NPM_CONFIG_ARCH = "x64"

[build.environment.VITE_GITHUB_TOKEN]
  # Add your GitHub token here for Netlify builds
  # You can also set this in Netlify dashboard for security

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
