[build]
  command = "npm install --platform=linux --arch=x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PLATFORM = "linux"
  NPM_CONFIG_ARCH = "x64"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
